### ISSUE TITLE
LS character will cause AttributeError: 'NoneType' object has no attribute 'groupdict'

### ISSUE THREAD

**Issue by FrancYescO** [huxuan/iptv-m3u-filter#16]
On a specific list, i have a channel name with a strange LS character that will break the script:
```
Traceback (most recent call last):
  File "/usr/local/bin/iptv-filter", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/iptvtools/iptv_filter.py", line 71, in main
    playlist.parse()
  File "/usr/local/lib/python3.6/dist-packages/iptvtools/models.py", line 68, in parse
    self._parse(self.args.inputs)
  File "/usr/local/lib/python3.6/dist-packages/iptvtools/models.py", line 95, in _parse
    current_item = parsers.parse_tag_inf(line)
  File "/usr/local/lib/python3.6/dist-packages/iptvtools/parsers.py", line 27, in parse_tag_inf
    res = match.groupdict()
AttributeError: 'NoneType' object has no attribute 'groupdict'
```

Copy and paste this block to an m3u and use this command `iptv-filter -i test.m3u --group-include "TESTING" -o TVList.m3u` to to try:
```
#EXTM3U
#EXTINF:-1 tvg-id="" tvg-name="normalname" tvg-logo="" group-title="GROUP",normalname
http://blalblalbllalv
#EXTINF:-1 tvg-id="" tvg-name="STRANGECHARACTER>>>  " tvg-logo="" group-title="GROUP",STRANGECHARACTER>>>  
http://testblabla/559864
```

using sublimetext you will clearly see the strange char:
![image](https://user-images.githubusercontent.com/4574593/141706219-309d6744-012c-48bf-991c-f2835753dda2.png)

**Comment by huxuan** [comment]
Hi @FrancYescO , thanks for the interest on `iptvtools`. May I know the purpose of the special character? Or more specifically, what is your suggestion on dealing with similar situations? For example, removing all special characters should be easy, but I am not sure whether there is any side effect.

**Comment by FrancYescO** [comment]
i think this character is just a bad typo from the list creator, best thing is to just leave the name as is, in my specific case i don't care this channel as my `--group-include` flag does not include it, but the issue is that iptv-filter is just unable to parse the input list and give an output if there is any channel with this weird character in.

**Comment by huxuan** [comment]
Actually, regular expression is used to parse each line of the list. Seems it is just the special character that leads to unexpected behavior of the parsing. If there is no special meanings at least we can filter those characters before throw it to the regular expression. I will double check whether it will affect the final output. For temporary mitigation, you can simple remove that character and run the script again. I was busy these days, so there might be no guarantee when it will be fixed. Anyway, thanks for the reporting, we can track the progress by this issue.

**Comment by FrancYescO** [comment]
Surely i can remove the character, but my main use of `iptvtools` is using it to parse a daily updated/downloaded list (mainly not under my control) from an automated sh cron script, so i just figured out that the update was broken and found this culprit as workaround i'll do some sort of pre-parsing before giving the downloaded m3u to `iptvtools` :D

**Comment by huxuan** [comment]
Gotcha, I can SOFT commit to fix this problem as early as possible which means it is expected to be done in this weekend. Feel free to ping me if you are in a hurry. :-)

**Comment by huxuan** [comment]
Hi @FrancYescO, a new version v0.2.5 [1] is uploaded. Could you please help me to double check it?

[1] https://pypi.org/project/iptvtools/0.2.5/

**Comment by FrancYescO** [comment]
Same error, probably actually is fully broken also for normal lists.

**Comment by huxuan** [comment]
OK, I yanked that release. Sorry for release a rush version on the way.

**Comment by huxuan** [comment]
Hi @FrancYescO Could you please provide the playlist or tell me how to get the error case for test?

**Comment by FrancYescO** [comment]
Copy and paste the list from the first post to an m3u file

**Comment by huxuan** [comment]
OK, I have to admit I underestimated the problem just now. Please help me to check the version 0.2.6 again. Thanks in advance.

https://pypi.org/project/iptvtools/0.2.6/

**Comment by FrancYescO** [comment]
At least in the test case, 0.2.6 is working, i'll back to you if i'll find any issue.
