### ISSUE TITLE
Issue when creating man pages

### ISSUE THREAD

**Issue by nt74** [huxuan/iptv-m3u-filter#30]
I have created an [AUR package](https://aur.archlinux.org/packages/python-iptvtools) for Arch Linux distro and discovered an issue when creating man pages using Sphinx tool.
It is solved by using sed command withing the PKGBUILD script for now, but it would be nice if You could fix this in the upstream package for version 0.2.10 (or a future release).

**Issue found in:**
`docs/parameters.rst:101: WARNING: Title underline too short.`

```
SKIP_CONNECTIVITY_CHECK
-----
```

**Should be format like this:**
```
SKIP_CONNECTIVITY_CHECK
-----------------------
```

**Comment by huxuan** [comment]
Thanks for the reporting. Just let me know if there is any further problem.
