### ISSUE TITLE
Please add the 'max-height' parameter

### ISSUE THREAD

**Issue by krasnh** [huxuan/iptv-m3u-filter#32]
'--min-height'
_HEIGHT is a dominant factor of stream quality, where 1080 in height means 1080p. It is necessary to set this filter if the stream is supposed to be shown on high resolution screens, e.g., a 4K TV._

--------------------------------------------------------------------

But on a small computer screen 1080p is unnecessary. Iron may also not be powerful enough. 576p or 720p is enough there. 

Please add '--max-height' to limit the video in the playlist to only 576p or 720p.

**Comment by huxuan** [comment]
It should be included in https://pypi.org/project/iptvtools/0.2.12/, just let me know if there is any problem. Thanks for using iptvtools!

**Comment by krasnh** [comment]
Thank you. Everything works as I wanted it to.
