### ISSUE TITLE
Iptv

### ISSUE THREAD

**Issue by teiken100** [huxuan/iptv-m3u-filter#7]
Καλησπέρα μοωρειτε να μου πείτε πως να δω κανάλια συνδρομιτιξσ

**Comment by teiken100** [comment]
Ote.novva

**Comment by huxuan** [comment]
@teiken100 Hi, from Google Translate, I think you are asking about how to watch those channels. Maybe a short answer is some software like vlc or kodi. Since this is a non-goal for this project, I will close this issue first. Thanks for your interests anyway.

**Comment by teiken100** [comment]
I have vls but I want to see Greek subscription channels like OTE.k nova.

Στις Σάβ, 11 Απρ 2020, 04:37 ο χρήστης Xuan (Sean) Hu <
notifications@github.com> έγραψε:

**Comment by teiken100** [comment]
there are some codecs to get in. and if so. where will I find it

Στις Σάβ, 11 Απρ 2020, 09:56 ο χρήστης Takis Mixas <takismix83@gmail.com>
έγραψε:
