### ISSUE TITLE
filter by group

### ISSUE THREAD

**Issue by FrancYescO** [huxuan/iptv-m3u-filter#9]
sometime i manage big list where i just want to get few group, is possible to add a flag to add a whitelist of wanted groups and ignore all other?

basically embed what this project do: https://github.com/dupontbenoit/iptv-m3u

**Comment by huxuan** [comment]
What about two args `--group-include` for whitlist and `--group-exclude` for blacklist? Any other more specific suggestions?

**Comment by FrancYescO** [comment]
i think these can be enought :)

Other useful thing would be a REGEX white/blacklist for the channel name, that can also be used for a custom channel sorting... but these are just ideas for what i do in other ways (sometime manually...) and liked to embed in this script

**Comment by huxuan** [comment]
Hi @FrancYescO , please help me to verify whether the #11 (version 0.2.2) meet your needs.
Just let me know if you have any further suggestions.

You can refer to the usage here: https://iptvtools.readthedocs.io/en/stable/scripts/iptv-filter.html

Thanks for using iptvtools.

**Comment by FrancYescO** [comment]
Thanks! this is what i was looking for

little bug, seems if group title is empty `group-title=""` it will be forcedly included in the filtered list also when using the --group-include list.

going to open another issue to explain better the custom ordering thing

**Comment by huxuan** [comment]
> little bug, seems if group title is empty `group-title=""` it will be forcedly included in the filtered list also when using the --group-include list.

Please help to check whether v0.2.3 #13 fix the issue.

**Comment by FrancYescO** [comment]
```
INFO:root:Retrieving playlists from file: tv_channels_64855285325176_plus.m3u
Traceback (most recent call last):
  File "/usr/local/bin/iptv-filter", line 8, in <module>
    sys.exit(main())
  File "/Library/Python/3.8/site-packages/iptvtools/iptv_filter.py", line 71, in main
    playlist.parse()
  File "/Library/Python/3.8/site-packages/iptvtools/models.py", line 68, in parse
    self._parse(self.args.inputs)
  File "/Library/Python/3.8/site-packages/iptvtools/models.py", line 101, in _parse
    if re.search(self.args.group_include, group):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/re.py", line 199, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

**Comment by FrancYescO** [comment]
confirmed working good with 0.2.4

**Comment by huxuan** [comment]
Thanks for the confirmation. I will close the issue then.

BTW, sorry for replied in the wrong thread.
